# Generated by Django 5.0.2 on 2024-03-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('service', 'service'), ('product', 'product')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
