# Generated by Django 5.0.2 on 2024-03-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0005_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
