# Generated by Django 5.0.2 on 2024-03-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0008_category_remove_product_digital_business_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
