# Generated by Django 5.0.3 on 2024-03-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0009_product_image'),
        ('eProx', '0010_business_logo'),
    ]

    operations = [
    ]
