# Generated by Django 5.0.2 on 2024-03-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0011_merge_0009_product_image_0010_business_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
