# Generated by Django 5.0.2 on 2024-03-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0013_product_digital_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
