# Generated by Django 5.0.2 on 2024-04-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0016_business_user_product_business'),
        ('eProx', '0016_business_user_product_product'),
    ]

    operations = [
    ]
