# Generated by Django 5.0.2 on 2024-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0020_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='logo1.jpg', upload_to='profile_pics/'),
        ),
    ]
