# Generated by Django 5.0.2 on 2024-04-20 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0020_alter_product_business_delete_profile'),
        ('eProx', '0021_alter_profile_images'),
    ]

    operations = [
    ]
