# Generated by Django 5.0.2 on 2024-04-21 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0022_merge_20240420_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eProx.business'),
        ),
    ]
