# Generated by Django 5.0.2 on 2024-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0024_order_status_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
