# Generated by Django 5.0.2 on 2024-04-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0026_alter_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
