# Generated by Django 5.0.4 on 2024-04-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0027_profile_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company',
            new_name='website',
        ),
    ]
