# Generated by Django 5.0.4 on 2024-04-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0029_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Company',
            field=models.CharField(default='None', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='General',
        ),
    ]
