# Generated by Django 5.0.4 on 2024-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0030_profile_company_profile_name_delete_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
