# Generated by Django 5.0.4 on 2024-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0031_alter_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Company',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
