# Generated by Django 5.0.4 on 2024-04-27 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0034_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
