# Generated by Django 5.0.4 on 2024-04-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0036_remove_product_digital'),
        ('eProx', '0038_product_upload_date'),
    ]

    operations = [
    ]
