# Generated by Django 5.0.2 on 2024-05-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0042_order_product'),
        
    ]

    operations = [
    ]
