# Generated by Django 5.0.4 on 2024-05-08 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0042_order_product'),
        ('order', '0004_remove_orderedproducts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.checkout'),
        ),
    ]
