# Generated by Django 5.0.4 on 2024-05-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0043_order_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
