# Generated by Django 5.0.2 on 2024-05-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0043_merge_0042_order_product_0042_product_slug'),
        ('eProx', '0045_customer_business'),
    ]

    operations = [
    ]
