# Generated by Django 5.0.4 on 2024-05-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='updated',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
