# Generated by Django 5.0.4 on 2024-05-07 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_checkout_city_remove_checkout_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.checkout'),
        ),
    ]
