# Generated by Django 5.0.4 on 2024-05-08 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderedproducts_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedproducts',
            name='product',
        ),
    ]
