# Generated by Django 5.0.4 on 2024-05-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderedproducts_product_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
