# Generated by Django 5.0.2 on 2024-05-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
