# Generated by Django 5.0.4 on 2024-05-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eProx', '0044_remove_shippingaddress_order_remove_orderitem_order_and_more'),
        ('order', '0008_alter_order_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='order.OrderedProducts', to='eProx.product'),
        ),
        migrations.AddField(
            model_name='orderedproducts',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.checkout'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedproducts',
            unique_together={('order', 'product')},
        ),
    ]
