# Generated by Django 5.0.4 on 2024-05-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_products_orderedproducts_orders_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
    ]
