# Generated by Django 5.0.4 on 2024-05-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products',
            new_name='product',
        ),
    ]
