# Generated by Django 5.0.4 on 2024-05-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_checkout_user_checkout_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.checkout'),
        ),
    ]
