# Generated by Django 5.0.4 on 2024-05-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_alter_order_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='customer',
            new_name='user',
        ),
    ]
