# Generated by Django 5.0.2 on 2024-05-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_product'),
        ('order', '0015_checkout_product'),
    ]

    operations = [
    ]
